# Generated by Django 4.0.3 on 2022-03-25 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('python_exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='author_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Автор создания'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='author_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update', to=settings.AUTH_USER_MODEL, verbose_name='Автор последних изменений'),
        ),
        migrations.DeleteModel(
            name='Commentary',
        ),
    ]
