# Generated by Django 4.0.3 on 2022-04-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_exercise', '0001_squashed_0009_place_remove_membership_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='complexity',
            field=models.IntegerField(verbose_name='Сложность'),
        ),
    ]
