# Generated by Django 4.0.3 on 2022-03-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_exercise', '0003_alter_exercise_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ('-time_update',), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
