# Generated by Django 4.0.3 on 2022-03-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_exercise', '0004_alter_exercise_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
