# Generated by Django 4.0.3 on 2022-03-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_exercise', '0005_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='complexity',
            field=models.IntegerField(default=1, verbose_name='Сложность'),
            preserve_default=False,
        ),
    ]
