# Generated by Django 4.0.3 on 2022-03-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_exercise', '0006_category_complexity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'permissions': (('can_set', 'can set'),), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
