# Generated by Django 4.0.3 on 2022-04-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_highlighted_snippet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='highlighted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
