# Generated by Django 4.0.3 on 2022-04-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_alter_userdata_photo_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('id',)},
        ),
    ]
